services:
  - type: web
    name: mvc-productos-basico5
    runtime: docker
    repo: https://github.com/MiguelGuevaraC/basico5
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: mvc-productos-basico5
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: mvc-productos-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_TTL_MINUTES
        value: 120
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: DB_SSLMODE
        value: "require"

databases:
  - name: mvc-productos-db
    databaseName: mvc_productos
    user: mvc_productos_user
    plan: starter
