services:
  - type: web
    name: mvc-productos-basico5
    runtime: docker
    repo: https://github.com/MiguelGuevaraC/basico5
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: mvc-productos-basico5
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d85pll3bc2fs73f24vng-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: basico5
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: enThbbnCah4DFliYI7lyCr9NpybSk27j
      - key: DB_SSLMODE
        value: prefer
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_TTL_MINUTES
        value: 120
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
